baseurl: /cv
permalink: pretty

port: 8000
exclude: ['README.md', 'LICENSE', 'gulpfile.js', "package.json", "package-lock.json", "node_modules"]

sass:
  sass_dir: assets/css
  style: :expanded

menu:
  - {name: profile, url: /}
  - {name: resume, url: /resume/}
  - {name: portfolio, url: /portfolio/}
  - {name: blog, url: /blog/}
  - {name: contact, url: /contact/}

social-icons:
  - {icon: "icon icon-facebook", name: "facebook"}
  - {icon: "icon icon-twitter", name: "twitter"}
  - {icon: "icon icon-dribbble", name: "dribbble"}
  - {icon: "icon icon-behance", name: "behance"}
  - {icon: "icon icon-instagram", name: "instagram"}